[package]
name = "quickcheck-derive"
version = "0.1.0"
edition = "2024"

[dependencies]
quickcheck = "1.0.3"
quickcheck-arbitrary-derive = { version = "0.2.2", path = "quickcheck-arbitrary-derive" }
quickcheck_macros = "1.1.0"
